version: "2"

linters:
  settings:
    staticcheck:
      checks:
        - "all"
        - "-QF*"
        - "-ST*"
        - "-S1009"
        - "-S1010"
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln

  exclusions:
    presets:
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - errcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
