package codegen

import (
	"fmt"
	"strings"
)

// SDK version ranges the emitted code targets. The generated invokers consume
// the cardinality-agnostic Invocation handle introduced in the 0.2.x SDKs;
// bump these alongside any emitted-shape change (the design's coordinated
// SDK + codegen versioning rule).
const (
	GoSDKRange = "github.com/openbindings/openbindings-go v0.2.x"
	TSSDKRange = "@openbindings/sdk ^0.2.0"
)

// EmitGo generates a Go typed-invoker file from a CodegenResult.
//
// The output is a struct named <InterfaceName>Invoker that wraps an
// *openbindings.OperationInvoker with the runtime interface bound at
// construction. Each operation becomes one method returning the typed,
// cardinality-agnostic invocation handle
// (*openbindings.TypedInvocation[I, O]) — never a Promise-style unary
// wrapper and never a *Stream twin. The caller decides cardinality through
// usage of the handle; the signature does not declare it.
func EmitGo(r *CodegenResult, packageName string) string {
	if packageName == "" {
		packageName = SanitizePackageName(r.InterfaceName)
	}

	var b strings.Builder

	b.WriteString("// Auto-generated by ob codegen — do not edit\n")
	b.WriteString(fmt.Sprintf("// Requires %s (the Invocation handle API).\n", GoSDKRange))
	b.WriteString(fmt.Sprintf("package %s\n\n", packageName))
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"encoding/json\"\n\n")
	b.WriteString("\topenbindings \"github.com/openbindings/openbindings-go\"\n")
	b.WriteString(")\n\n")

	// Types.
	if len(r.Types) > 0 {
		b.WriteString("// --- Types ---\n\n")
		for _, td := range r.Types {
			emitGoStruct(&b, td)
		}
	}

	// Per-call options.
	b.WriteString("// InvokerCallOpts are the optional per-call arguments accepted by every\n")
	b.WriteString("// generated method. Cancellation and deadlines flow through the ctx passed\n")
	b.WriteString("// to the method (and to the handle's Write/Read).\n")
	b.WriteString("type InvokerCallOpts struct {\n")
	b.WriteString("\t// Context is per-call invocation context (credentials, configuration).\n")
	b.WriteString("\tContext map[string]any\n")
	b.WriteString("\t// BindingKey pins a specific binding instead of the default selection.\n")
	b.WriteString("\tBindingKey string\n")
	b.WriteString("}\n\n")

	// Typed invoker.
	invokerName := r.InterfaceName + "Invoker"
	b.WriteString(goDocComment(fmt.Sprintf("%s exposes typed methods for the operations declared by the codegen-time OBI contract. Each method returns the cardinality-agnostic invocation handle: write inputs until done, read outputs until done — one shape for unary, streaming, and bidirectional bindings. For an operation you are confident yields exactly one output, drive the handle and use openbindings.Single over its Outputs().", invokerName), ""))
	b.WriteString(fmt.Sprintf("type %s struct {\n", invokerName))
	b.WriteString("\tinvoker *openbindings.OperationInvoker\n")
	b.WriteString("\tiface   *openbindings.Interface\n")
	b.WriteString("}\n\n")

	// Contract accessor — exposes the OBI contract this invoker was generated
	// against, for opt-in compatibility validation by callers.
	b.WriteString(fmt.Sprintf("// %sContract returns the OBI contract this invoker was generated against.\n", invokerName))
	b.WriteString("// Operations + schemas only; bindings are stripped for HTTP-fetchable sources.\n")
	b.WriteString(fmt.Sprintf("func %sContract() *openbindings.Interface {\n", invokerName))
	b.WriteString("\treturn mustParseInterface()\n")
	b.WriteString("}\n\n")

	// Constructor binds the runtime interface once.
	b.WriteString(fmt.Sprintf("// New%s wraps an OperationInvoker with typed methods, binding the\n", invokerName))
	b.WriteString("// runtime interface once at construction. Pass a nil iface to dispatch\n")
	b.WriteString("// against the embedded codegen-time contract. To target several providers\n")
	b.WriteString("// of the same contract, construct one typed invoker per provider.\n")
	b.WriteString(fmt.Sprintf("func New%s(invoker *openbindings.OperationInvoker, iface *openbindings.Interface) *%s {\n", invokerName, invokerName))
	b.WriteString("\tif iface == nil {\n")
	b.WriteString("\t\tiface = mustParseInterface()\n")
	b.WriteString("\t}\n")
	b.WriteString(fmt.Sprintf("\treturn &%s{invoker: invoker, iface: iface}\n", invokerName))
	b.WriteString("}\n\n")

	// Operation methods.
	for _, op := range r.Operations {
		emitGoMethod(&b, op, invokerName)
	}

	// Embedded interface.
	b.WriteString("// --- Embedded interface ---\n\n")
	b.WriteString("func mustParseInterface() *openbindings.Interface {\n")
	b.WriteString("\tvar iface openbindings.Interface\n")
	b.WriteString("\tif err := json.Unmarshal([]byte(interfaceJSON), &iface); err != nil {\n")
	b.WriteString("\t\tpanic(\"ob codegen: embedded interface is invalid: \" + err.Error())\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn &iface\n")
	b.WriteString("}\n\n")

	b.WriteString("// Contract only: operations + schemas, no bindings/sources/transforms\n")
	b.WriteString(fmt.Sprintf("const interfaceJSON = `%s`\n", goEscapeRawString(string(r.RawOBI))))

	return b.String()
}

func emitGoStruct(b *strings.Builder, td TypeDef) {
	if td.Description != "" {
		b.WriteString(goDocComment(fmt.Sprintf("%s — %s", td.Name, td.Description), ""))
	}
	b.WriteString(fmt.Sprintf("type %s struct {\n", td.Name))
	for _, f := range td.Fields {
		if f.Description != "" {
			b.WriteString(goDocComment(f.Description, "\t"))
		}
		tag := f.JSONName
		if !f.Required {
			tag += ",omitempty"
		}
		b.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", f.Name, goTypeRef(f.Type, !f.Required), tag))
	}
	b.WriteString("}\n\n")
}

func emitGoMethod(b *strings.Builder, op OperationSig, invokerName string) {
	methodName := toPascalCase(op.Key)

	inputType := "any"
	if op.Input != nil {
		inputType = goTypeRef(*op.Input, false)
	}
	outputType := "any"
	if op.Output != nil {
		outputType = goTypeRef(*op.Output, false)
	}

	// Doc comment. The handle shape is the same for every cardinality, so the
	// doc spells out the driving pattern instead of a per-cardinality API.
	var doc strings.Builder
	doc.WriteString(fmt.Sprintf("%s returns the invocation handle for the %s operation.", methodName, op.Key))
	if op.Description != "" {
		doc.WriteString("\n")
		doc.WriteString(op.Description)
	}
	if op.Input != nil {
		doc.WriteString(fmt.Sprintf("\n\nWrite the %s input(s) on the handle; read outputs from Outputs() to io.EOF or a terminal error.", inputType))
	} else {
		doc.WriteString("\n\nThe operation declares no input; read outputs from Outputs() to io.EOF or a terminal error.")
	}
	if op.Deprecated {
		doc.WriteString("\n\nDeprecated: this operation is deprecated.")
	}
	b.WriteString(goDocComment(doc.String(), ""))

	b.WriteString(fmt.Sprintf("func (inv *%s) %s(ctx context.Context, opts InvokerCallOpts) *openbindings.TypedInvocation[%s, %s] {\n",
		invokerName, methodName, inputType, outputType))
	b.WriteString(fmt.Sprintf("\treturn openbindings.NewTypedInvocation[%s, %s](inv.invoker.Invoke(ctx, &openbindings.OperationInvocationArgs{\n", inputType, outputType))
	b.WriteString("\t\tInterface:  inv.iface,\n")
	b.WriteString(fmt.Sprintf("\t\tOperation:  \"%s\",\n", op.Key))
	b.WriteString("\t\tContext:    opts.Context,\n")
	b.WriteString("\t\tBindingKey: opts.BindingKey,\n")
	b.WriteString("\t}))\n")
	b.WriteString("}\n\n")
}

// goTypeRef converts an IR TypeRef to a Go type string.
// optional indicates whether the field is optional (use pointer for value types).
func goTypeRef(ref TypeRef, optional bool) string {
	var base string
	switch ref.Kind {
	case KindPrimitive:
		switch ref.Primitive {
		case "string":
			base = "string"
		case "number":
			base = "float64"
		case "integer":
			base = "int64"
		case "boolean":
			base = "bool"
		default:
			base = "any"
		}
	case KindNamed:
		base = ref.Name
	case KindArray:
		if ref.Items != nil {
			base = "[]" + goTypeRef(*ref.Items, false)
		} else {
			base = "[]any"
		}
	case KindMap:
		valType := "any"
		if ref.Values != nil {
			valType = goTypeRef(*ref.Values, false)
		}
		base = "map[string]" + valType
	case KindUnion:
		// Go doesn't have union types; use any.
		base = "any"
	default:
		base = "any"
	}

	if ref.Nullable || (optional && isPrimitiveGoType(base)) {
		return "*" + base
	}
	return base
}

func isPrimitiveGoType(t string) bool {
	switch t {
	case "string", "float64", "int64", "bool":
		return true
	}
	return false
}

func goDocComment(text, indent string) string {
	lines := strings.Split(text, "\n")
	var b strings.Builder
	for _, line := range lines {
		if line == "" {
			b.WriteString(fmt.Sprintf("%s//\n", indent))
		} else {
			b.WriteString(fmt.Sprintf("%s// %s\n", indent, line))
		}
	}
	return b.String()
}

func goEscapeRawString(s string) string {
	// Raw strings can't contain backticks. Replace with string concat.
	return strings.ReplaceAll(s, "`", "` + \"`\" + `")
}
