package codegen

import (
	"fmt"
	"go/format"
	"strings"
)

// SDK version ranges the emitted code targets. The generated signatures consume
// the OperationSignature/Invoke surface introduced in the 0.2.x SDKs; bump these
// alongside any emitted-shape change (the design's coordinated SDK + codegen
// versioning rule).
const (
	GoSDKRange = "github.com/openbindings/openbindings-go v0.2.x"
	TSSDKRange = "@openbindings/sdk ^0.2.0"
)

// EmitGo generates a Go signature file from a CodegenResult.
//
// The output is the per-operation input/output type structs plus an
// OperationSignatures namespace: a package-level value of a named struct type
// holding one invoke.OperationSignature[I, O] per operation. Callers
// invoke with the free verb, supplying the runtime interface:
//
//	call := invoke.Invoke(ctx, invoker, obi, pkg.OperationSignatures.GetMenu)
//	out, err := invoke.Single(ctx, call.Outputs())
//
// There are no per-operation methods, no bound invoker struct, and no embedded
// contract: the interface is the runtime bundle, passed to Invoke, never
// codegenned. Cardinality lives in the binding and the handle, never in the
// generated signature. The result is gofmt-clean; if the emitted source somehow
// does not parse, the raw text is returned so the caller can see what broke.
func EmitGo(r *CodegenResult, packageName string) string {
	if packageName == "" {
		packageName = SanitizePackageName(r.InterfaceName)
	}

	var b strings.Builder

	b.WriteString("// Auto-generated by ob codegen — do not edit\n")
	b.WriteString(fmt.Sprintf("// Requires %s (the OperationSignature/Invoke API).\n", GoSDKRange))
	b.WriteString(fmt.Sprintf("package %s\n\n", packageName))
	b.WriteString("import \"github.com/openbindings/openbindings-go/invoke\"\n\n")

	// Types: per-operation I/O structs plus any named schemas they share. A
	// schema referenced by several operations is emitted once and reused, so
	// type identity is preserved across operations.
	if len(r.Types) > 0 {
		b.WriteString("// --- Types ---\n\n")
		for _, td := range r.Types {
			emitGoStruct(&b, td)
		}
	}

	// Operation signatures.
	b.WriteString("// --- Operation signatures ---\n\n")
	emitGoSignatures(&b, r)
	if len(r.Dependencies) > 0 {
		b.WriteString("\n// --- Dependency signatures ---\n\n")
		emitGoDependencySignatures(&b, r)
	}

	src := b.String()
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return src
	}
	return string(formatted)
}

func emitGoDependencySignatures(b *strings.Builder, r *CodegenResult) {
	b.WriteString(goDocComment("dependencySignatures is the namespace type holding one generated identity per named OBI dependency. Use the DependencySignatures value below, not this type directly.", ""))
	b.WriteString("type dependencySignatures struct {\n")
	for _, dependency := range r.Dependencies {
		field := toPascalCase(dependency.Name)
		b.WriteString(goDocComment(fmt.Sprintf("%s is the %q dependency; its I/O types are derived from operation %q.", field, dependency.Key, dependency.OperationKey), "\t"))
		b.WriteString(fmt.Sprintf("\t%s invoke.DependencySignature[%s, %s]\n",
			field, goSigType(dependency.Input), goSigType(dependency.Output)))
	}
	b.WriteString("}\n\n")
	b.WriteString(goDocComment("DependencySignatures holds one typed identity per named dependency declared by the codegen-time OBI. Each I/O type is mechanically inherited from its referenced operation.", ""))
	b.WriteString("var DependencySignatures = dependencySignatures{\n")
	for _, dependency := range r.Dependencies {
		b.WriteString(fmt.Sprintf("\t%s: invoke.NewDependencySignatureForOperation(%q, OperationSignatures.%s),\n",
			toPascalCase(dependency.Name), dependency.Key, toPascalCase(dependency.OperationName)))
	}
	b.WriteString("}\n")
}

// emitGoSignatures writes the OperationSignatures namespace: a named struct type
// (so each operation's description and deprecation ride its field and surface in
// go doc / IDE hover) plus the package-level value built from it.
func emitGoSignatures(b *strings.Builder, r *CodegenResult) {
	b.WriteString(goDocComment("operationSignatures is the namespace type holding one typed signature per operation. Use the OperationSignatures value below, not this type directly.", ""))
	b.WriteString("type operationSignatures struct {\n")
	for _, op := range r.Operations {
		field := toPascalCase(op.Name)
		var doc strings.Builder
		if op.Description != "" {
			doc.WriteString(op.Description)
		} else {
			doc.WriteString(fmt.Sprintf("%s is the %q operation.", field, op.Key))
		}
		if op.Deprecated {
			doc.WriteString("\n\nDeprecated: this operation is deprecated.")
		}
		b.WriteString(goDocComment(doc.String(), "\t"))
		b.WriteString(fmt.Sprintf("\t%s invoke.OperationSignature[%s, %s]\n",
			field, goSigType(op.Input), goSigType(op.Output)))
	}
	b.WriteString("}\n\n")

	// Package-level namespace value, built through the SDK constructor (the
	// signature's key field is unexported, so a struct literal won't do).
	example := toPascalCase(r.Operations[0].Name)
	doc := fmt.Sprintf("OperationSignatures holds one typed signature per operation declared by the codegen-time OBI. Pass the runtime interface and a signature to invoke.Invoke; input flows through the handle's Write and output through Single (the typed [I, O] is not a unary in/out shortcut):\n\n\tcall := invoke.Invoke(ctx, invoker, obi, OperationSignatures.%s)\n\tout, err := invoke.Single(ctx, call.Outputs())", example)
	b.WriteString(goDocComment(doc, ""))
	b.WriteString("var OperationSignatures = operationSignatures{\n")
	for _, op := range r.Operations {
		b.WriteString(fmt.Sprintf("\t%s: invoke.NewOperationSignature[%s, %s](%q),\n",
			toPascalCase(op.Name), goSigType(op.Input), goSigType(op.Output), op.Key))
	}
	b.WriteString("}\n")
}

// goSigType renders an operation input/output TypeRef as a Go type, defaulting
// to any when the operation declares no schema.
func goSigType(ref *TypeRef) string {
	if ref == nil {
		return "any"
	}
	return goTypeRef(*ref, false)
}

func emitGoStruct(b *strings.Builder, td TypeDef) {
	if td.Description != "" {
		b.WriteString(goDocComment(fmt.Sprintf("%s — %s", td.Name, td.Description), ""))
	}
	b.WriteString(fmt.Sprintf("type %s struct {\n", td.Name))
	for _, f := range td.Fields {
		if f.Description != "" {
			b.WriteString(goDocComment(f.Description, "\t"))
		}
		tag := f.JSONName
		if !f.Required {
			tag += ",omitempty"
		}
		b.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", f.Name, goTypeRef(f.Type, !f.Required), tag))
	}
	b.WriteString("}\n\n")
}

// goTypeRef converts an IR TypeRef to a Go type string.
// optional indicates whether the field is optional (use pointer for value types).
func goTypeRef(ref TypeRef, optional bool) string {
	var base string
	switch ref.Kind {
	case KindPrimitive:
		switch ref.Primitive {
		case "string":
			base = "string"
		case "number":
			base = "float64"
		case "integer":
			base = "int64"
		case "boolean":
			base = "bool"
		default:
			base = "any"
		}
	case KindNamed:
		base = ref.Name
	case KindArray:
		if ref.Items != nil {
			base = "[]" + goTypeRef(*ref.Items, false)
		} else {
			base = "[]any"
		}
	case KindMap:
		valType := "any"
		if ref.Values != nil {
			valType = goTypeRef(*ref.Values, false)
		}
		base = "map[string]" + valType
	case KindUnion:
		// Go doesn't have union types; use any.
		base = "any"
	default:
		base = "any"
	}

	if ref.Nullable || (optional && isPrimitiveGoType(base)) {
		return "*" + base
	}
	return base
}

func isPrimitiveGoType(t string) bool {
	switch t {
	case "string", "float64", "int64", "bool":
		return true
	}
	return false
}

func goDocComment(text, indent string) string {
	lines := strings.Split(text, "\n")
	var b strings.Builder
	for _, line := range lines {
		if line == "" {
			b.WriteString(fmt.Sprintf("%s//\n", indent))
		} else {
			b.WriteString(fmt.Sprintf("%s// %s\n", indent, line))
		}
	}
	return b.String()
}
