package codegen

import (
	"fmt"
	"strings"
)

// EmitGo generates a Go client file from a CodegenResult.
func EmitGo(r *CodegenResult, packageName string) string {
	if packageName == "" {
		packageName = SanitizePackageName(r.InterfaceName)
	}

	var b strings.Builder

	b.WriteString("// Auto-generated by ob codegen — do not edit\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", packageName))
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"fmt\"\n\n")
	b.WriteString("\topenbindings \"github.com/openbindings/openbindings-go\"\n")
	b.WriteString(")\n\n")

	// Types.
	if len(r.Types) > 0 {
		b.WriteString("// --- Types ---\n\n")
		for _, td := range r.Types {
			emitGoStruct(&b, td)
		}
	}

	// Client struct.
	clientName := r.InterfaceName + "Client"
	if r.Description != "" {
		b.WriteString(goDocComment(fmt.Sprintf("%s wraps an InterfaceClient with typed methods.", clientName), ""))
	}
	b.WriteString(fmt.Sprintf("type %s struct {\n", clientName))
	b.WriteString("\tclient *openbindings.InterfaceClient\n")
	b.WriteString("}\n\n")

	// Constructor.
	b.WriteString(fmt.Sprintf("// New%s creates a new typed client.\n", clientName))
	b.WriteString(fmt.Sprintf("func New%s(executor *openbindings.OperationExecutor, opts ...openbindings.InterfaceClientOption) *%s {\n", clientName, clientName))
	b.WriteString(fmt.Sprintf("\treturn &%s{\n", clientName))
	b.WriteString("\t\tclient: openbindings.NewInterfaceClient(mustParseInterface(), executor, opts...),\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	// Resolve method.
	b.WriteString(fmt.Sprintf("// Resolve connects the client to a target.\n"))
	b.WriteString(fmt.Sprintf("func (c *%s) Resolve(ctx context.Context, target string) error {\n", clientName))
	b.WriteString("\treturn c.client.Resolve(ctx, target)\n")
	b.WriteString("}\n\n")

	// State method.
	b.WriteString(fmt.Sprintf("// State returns the current client state.\n"))
	b.WriteString(fmt.Sprintf("func (c *%s) State() openbindings.InterfaceClientState {\n", clientName))
	b.WriteString("\treturn c.client.State()\n")
	b.WriteString("}\n\n")

	// Operation methods.
	for _, op := range r.Operations {
		emitGoMethod(&b, op, clientName)
	}

	// Helpers.
	emitGoHelpers(&b)

	// Embedded interface.
	b.WriteString("// --- Embedded interface ---\n\n")
	b.WriteString("func mustParseInterface() *openbindings.Interface {\n")
	b.WriteString("\tvar iface openbindings.Interface\n")
	b.WriteString("\tif err := json.Unmarshal([]byte(interfaceJSON), &iface); err != nil {\n")
	b.WriteString("\t\tpanic(\"ob codegen: embedded interface is invalid: \" + err.Error())\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn &iface\n")
	b.WriteString("}\n\n")

	b.WriteString("// Contract only: operations + schemas, no bindings/sources/transforms\n")
	b.WriteString(fmt.Sprintf("const interfaceJSON = `%s`\n", goEscapeRawString(string(r.RawOBI))))

	return b.String()
}

func emitGoStruct(b *strings.Builder, td TypeDef) {
	if td.Description != "" {
		b.WriteString(goDocComment(fmt.Sprintf("%s — %s", td.Name, td.Description), ""))
	}
	b.WriteString(fmt.Sprintf("type %s struct {\n", td.Name))
	for _, f := range td.Fields {
		if f.Description != "" {
			b.WriteString(goDocComment(f.Description, "\t"))
		}
		tag := f.JSONName
		if !f.Required {
			tag += ",omitempty"
		}
		b.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", f.Name, goTypeRef(f.Type, !f.Required), tag))
	}
	b.WriteString("}\n\n")
}

func emitGoMethod(b *strings.Builder, op OperationSig, clientName string) {
	methodName := toPascalCase(op.Key)

	// Doc comment.
	if op.Description != "" || op.Deprecated {
		var doc strings.Builder
		doc.WriteString(fmt.Sprintf("%s executes the %s operation.", methodName, op.Key))
		if op.Description != "" {
			doc.WriteString("\n")
			doc.WriteString(op.Description)
		}
		if op.Deprecated {
			doc.WriteString("\n\nDeprecated: this operation is deprecated.")
		}
		b.WriteString(goDocComment(doc.String(), ""))
	}

	// All operations use unary pattern for v1.
	hasInput := op.Input != nil
	hasOutput := op.Output != nil

	// Build signature.
	var params []string
	params = append(params, "ctx context.Context")
	if hasInput {
		inputType := goTypeRef(*op.Input, false)
		// Use pointer for named/struct inputs.
		if op.Input.Kind == KindNamed {
			params = append(params, "input *"+inputType)
		} else {
			params = append(params, "input "+inputType)
		}
	}

	outputType := "any"
	if hasOutput {
		outputType = goTypeRef(*op.Output, false)
	}

	// For array outputs, return the value directly (not a pointer to a slice).
	returnsSlice := hasOutput && op.Output.Kind == KindArray

	if returnsSlice {
		b.WriteString(fmt.Sprintf("func (c *%s) %s(%s) (%s, error) {\n",
			clientName, methodName, strings.Join(params, ", "), outputType))
	} else {
		b.WriteString(fmt.Sprintf("func (c *%s) %s(%s) (*%s, error) {\n",
			clientName, methodName, strings.Join(params, ", "), outputType))
	}

	inputArg := "nil"
	if hasInput {
		inputArg = "input"
	}

	if returnsSlice {
		b.WriteString(fmt.Sprintf("\tv, err := execUnary[%s](ctx, c.client, \"%s\", %s)\n", outputType, op.Key, inputArg))
		b.WriteString("\tif err != nil {\n")
		b.WriteString("\t\treturn nil, err\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn *v, nil\n")
	} else {
		b.WriteString(fmt.Sprintf("\treturn execUnary[%s](ctx, c.client, \"%s\", %s)\n", outputType, op.Key, inputArg))
	}
	b.WriteString("}\n\n")
}

func emitGoHelpers(b *strings.Builder) {
	b.WriteString("// --- Helpers ---\n\n")

	// execUnary.
	b.WriteString("func execUnary[T any](ctx context.Context, c *openbindings.InterfaceClient, op string, input any) (*T, error) {\n")
	b.WriteString("\tch, err := c.Execute(ctx, op, input)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn nil, err\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdefer func() {\n")
	b.WriteString("\t\tfor range ch {} // drain remaining events\n")
	b.WriteString("\t}()\n")
	b.WriteString("\tfor event := range ch {\n")
	b.WriteString("\t\tif event.Error != nil {\n")
	b.WriteString("\t\t\treturn nil, fmt.Errorf(\"%s: %s\", event.Error.Code, event.Error.Message)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tb, err := json.Marshal(event.Data)\n")
	b.WriteString("\t\tif err != nil {\n")
	b.WriteString("\t\t\treturn nil, fmt.Errorf(\"marshal event data: %w\", err)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tvar result T\n")
	b.WriteString("\t\tif err := json.Unmarshal(b, &result); err != nil {\n")
	b.WriteString("\t\t\treturn nil, fmt.Errorf(\"unmarshal %s output: %w\", op, err)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\treturn &result, nil\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil, fmt.Errorf(\"%s: no events received\", op)\n")
	b.WriteString("}\n\n")

}

// goTypeRef converts an IR TypeRef to a Go type string.
// optional indicates whether the field is optional (use pointer for value types).
func goTypeRef(ref TypeRef, optional bool) string {
	var base string
	switch ref.Kind {
	case KindPrimitive:
		switch ref.Primitive {
		case "string":
			base = "string"
		case "number":
			base = "float64"
		case "integer":
			base = "int64"
		case "boolean":
			base = "bool"
		default:
			base = "any"
		}
	case KindNamed:
		base = ref.Name
	case KindArray:
		if ref.Items != nil {
			base = "[]" + goTypeRef(*ref.Items, false)
		} else {
			base = "[]any"
		}
	case KindMap:
		valType := "any"
		if ref.Values != nil {
			valType = goTypeRef(*ref.Values, false)
		}
		base = "map[string]" + valType
	case KindUnion:
		// Go doesn't have union types; use any.
		base = "any"
	default:
		base = "any"
	}

	if ref.Nullable || (optional && isPrimitiveGoType(base)) {
		return "*" + base
	}
	return base
}

func isPrimitiveGoType(t string) bool {
	switch t {
	case "string", "float64", "int64", "bool":
		return true
	}
	return false
}

func goDocComment(text, indent string) string {
	lines := strings.Split(text, "\n")
	var b strings.Builder
	for _, line := range lines {
		if line == "" {
			b.WriteString(fmt.Sprintf("%s//\n", indent))
		} else {
			b.WriteString(fmt.Sprintf("%s// %s\n", indent, line))
		}
	}
	return b.String()
}

func goEscapeRawString(s string) string {
	// Raw strings can't contain backticks. Replace with string concat.
	return strings.ReplaceAll(s, "`", "` + \"`\" + `")
}
