package codegen

import (
	"fmt"
	"strings"
)

// EmitTypeScript generates a TypeScript client file from a CodegenResult.
func EmitTypeScript(r *CodegenResult) string {
	var b strings.Builder

	// Check if any generated type collides with SDK imports.
	hasExecutionOptions := false
	for _, td := range r.Types {
		if td.Name == "ExecutionOptions" {
			hasExecutionOptions = true
			break
		}
	}

	execOptsType := "ExecutionOptions"
	if hasExecutionOptions {
		execOptsType = "SDKExecutionOptions"
	}

	// --- Imports ---
	b.WriteString("// Auto-generated by ob codegen — do not edit\n")
	b.WriteString("import {\n")
	b.WriteString("  InterfaceClient,\n")
	b.WriteString("  OperationExecutor,\n")
	b.WriteString("  MemoryStore,\n")
	b.WriteString("  normalizeContextKey,\n")
	b.WriteString("  type InterfaceClientOptions,\n")
	b.WriteString("  type OBInterface,\n")
	b.WriteString("  type StreamEvent,\n")
	b.WriteString("  type ContextStore,\n")
	b.WriteString("  type PlatformCallbacks,\n")
	if !hasExecutionOptions {
		b.WriteString("  type ExecutionOptions,\n")
	} else {
		b.WriteString("  type ExecutionOptions as SDKExecutionOptions,\n")
	}
	b.WriteString("} from \"@openbindings/sdk\";\n\n")

	// --- Types ---
	if len(r.Types) > 0 {
		b.WriteString("// --- Types ---\n\n")
		for _, td := range r.Types {
			emitTSInterface(&b, td)
		}
	}

	// --- TypedStreamEvent ---
	b.WriteString("// --- Stream event ---\n\n")
	b.WriteString("export interface TypedStreamEvent<T> {\n")
	b.WriteString("  data?: T;\n")
	b.WriteString("  error?: { code: string; message: string; details?: unknown };\n")
	b.WriteString("}\n\n")

	// --- ClientOperationError ---
	b.WriteString("// --- Error ---\n\n")
	b.WriteString("export class ClientOperationError extends Error {\n")
	b.WriteString("  readonly code: string;\n")
	b.WriteString("  readonly details?: unknown;\n")
	b.WriteString("  constructor(code: string, message: string, details?: unknown) {\n")
	b.WriteString("    super(message);\n")
	b.WriteString("    this.name = 'ClientOperationError';\n")
	b.WriteString("    this.code = code;\n")
	b.WriteString("    this.details = details;\n")
	b.WriteString("  }\n")
	b.WriteString("}\n\n")

	// --- ConnectOptions ---
	b.WriteString("// --- Options ---\n\n")
	b.WriteString("export interface ConnectOptions {\n")
	b.WriteString("  bearerToken?: string;\n")
	b.WriteString("  contextStore?: ContextStore;\n")
	b.WriteString("  platformCallbacks?: PlatformCallbacks;\n")
	b.WriteString("  signal?: AbortSignal;\n")
	b.WriteString("}\n\n")


	// --- Operations type map ---
	b.WriteString("// --- Operation type map ---\n\n")
	b.WriteString(fmt.Sprintf("type %sOperations = {\n", r.InterfaceName))
	for _, op := range r.Operations {
		b.WriteString(fmt.Sprintf("  %s: {", op.Key))
		parts := []string{}
		if op.Input != nil {
			parts = append(parts, fmt.Sprintf(" input: %s;", tsTypeRef(*op.Input)))
		}
		if op.Output != nil {
			parts = append(parts, fmt.Sprintf(" output: %s;", tsTypeRef(*op.Output)))
		}
		if len(parts) > 0 {
			b.WriteString(strings.Join(parts, ""))
			b.WriteString(" };\n")
		} else {
			b.WriteString(" };\n")
		}
	}
	b.WriteString("};\n\n")

	// --- Client class ---
	b.WriteString("// --- Client ---\n\n")
	if r.Description != "" {
		b.WriteString(tsDocComment(r.Description, ""))
	}

	opsType := fmt.Sprintf("%sOperations", r.InterfaceName)
	b.WriteString(fmt.Sprintf("export class %sClient {\n", r.InterfaceName))
	b.WriteString("  private executor: OperationExecutor;\n")
	b.WriteString(fmt.Sprintf("  private _client: InterfaceClient<%s> | null = null;\n", opsType))

	// Constructor — takes a pre-built OperationExecutor, matching the Go codegen pattern.
	// The caller configures the executor with whatever options they need (transform evaluator,
	// context store, callbacks, binding selector, etc.) before passing it in.
	b.WriteString("\n  constructor(executor: OperationExecutor) {\n")
	b.WriteString("    this.executor = executor;\n")
	b.WriteString("  }\n\n")

	// connect method.
	b.WriteString("  /**\n")
	b.WriteString("   * Connect to a service. Resolves the OBI, sets up auth context,\n")
	b.WriteString("   * and prepares the client for operation calls.\n")
	b.WriteString("   */\n")
	b.WriteString("  async connect(url: string, opts?: ConnectOptions): Promise<void> {\n")
	b.WriteString("    const store = opts?.contextStore ?? this.executor.contextStore ?? new MemoryStore();\n")
	b.WriteString("    const callbacks = opts?.platformCallbacks ?? this.executor.platformCallbacks;\n")
	b.WriteString("    if (opts?.bearerToken) {\n")
	b.WriteString("      const key = normalizeContextKey(url);\n")
	b.WriteString("      await store.set(key, { bearerToken: opts.bearerToken });\n")
	b.WriteString("    }\n")
	b.WriteString("    const executor = this.executor.withRuntime(store, callbacks);\n")
	b.WriteString(fmt.Sprintf("    const client = new InterfaceClient<%s>(INTERFACE, executor, {\n", opsType))
	b.WriteString("      contextStore: store,\n")
	b.WriteString("      platformCallbacks: callbacks,\n")
	b.WriteString("    });\n")
	b.WriteString("    await client.resolve(url, { signal: opts?.signal });\n")
	b.WriteString("    if (client.state.kind === 'error') {\n")
	b.WriteString("      throw new Error(client.state.message);\n")
	b.WriteString("    }\n")
	b.WriteString("    this._client = client;\n")
	b.WriteString("  }\n\n")

	// Private client getter.
	b.WriteString(fmt.Sprintf("  private get client(): InterfaceClient<%s> {\n", opsType))
	b.WriteString("    if (!this._client) throw new Error('Not connected. Call connect() first.');\n")
	b.WriteString("    return this._client;\n")
	b.WriteString("  }\n\n")

	// Operation methods — unary + stream.
	for _, op := range r.Operations {
		emitTSUnaryMethod(&b, op, execOptsType)
		b.WriteString("\n")
		emitTSStreamMethod(&b, op, execOptsType)
		b.WriteString("\n")
	}

	b.WriteString("}\n\n")

	// --- Embedded interface ---
	b.WriteString("// --- Embedded interface ---\n\n")
	b.WriteString("const INTERFACE: OBInterface = JSON.parse('")
	b.WriteString(tsEscapeSingleQuoteString(string(r.RawOBI)))
	b.WriteString("');\n")

	return b.String()
}

// emitTSUnaryMethod emits a Promise-returning convenience method.
func emitTSUnaryMethod(b *strings.Builder, op OperationSig, execOptsType string) {
	methodName := toCamelCase(op.Key)

	isVoid := op.Output == nil
	outputType := "unknown"
	if !isVoid {
		outputType = tsTypeRef(*op.Output)
	}

	// Doc comment.
	if op.Description != "" || op.Deprecated {
		b.WriteString("  /**\n")
		if op.Deprecated {
			b.WriteString("   * @deprecated\n")
		}
		if op.Description != "" {
			b.WriteString(fmt.Sprintf("   * %s\n", op.Description))
		}
		b.WriteString("   */\n")
	}

	// Signature.
	var params []string
	if op.Input != nil {
		params = append(params, fmt.Sprintf("input: %s", tsTypeRef(*op.Input)))
	}
	params = append(params, fmt.Sprintf("options?: %s", execOptsType))

	returnType := outputType
	if isVoid {
		returnType = "void"
	}
	b.WriteString(fmt.Sprintf("  async %s(%s): Promise<%s> {\n",
		methodName, strings.Join(params, ", "), returnType))

	// Body.
	inputArg := "undefined"
	if op.Input != nil {
		inputArg = "input"
	}
	b.WriteString(fmt.Sprintf("    for await (const event of this.client.execute(\"%s\", %s, options)) {\n", op.Key, inputArg))
	b.WriteString("      if (event.error) {\n")
	b.WriteString("        throw new ClientOperationError(event.error.code, event.error.message, event.error.details);\n")
	b.WriteString("      }\n")
	if isVoid {
		b.WriteString("      return;\n")
	} else {
		b.WriteString("      if (event.data !== undefined) {\n")
		b.WriteString(fmt.Sprintf("        return event.data as %s;\n", outputType))
		b.WriteString("      }\n")
	}
	b.WriteString("    }\n")
	if !isVoid {
		b.WriteString(fmt.Sprintf("    throw new ClientOperationError(\"no_data\", \"%s returned no data\");\n", op.Key))
	}
	b.WriteString("  }\n")
}

// emitTSStreamMethod emits an AsyncGenerator-returning method with Stream suffix.
func emitTSStreamMethod(b *strings.Builder, op OperationSig, execOptsType string) {
	methodName := toCamelCase(op.Key) + "Stream"

	outputType := "unknown"
	if op.Output != nil {
		outputType = tsTypeRef(*op.Output)
	}

	// Doc comment.
	b.WriteString(fmt.Sprintf("  /** Stream variant of %s. */\n", toCamelCase(op.Key)))

	// Signature.
	var params []string
	if op.Input != nil {
		params = append(params, fmt.Sprintf("input: %s", tsTypeRef(*op.Input)))
	}
	params = append(params, fmt.Sprintf("options?: %s", execOptsType))

	b.WriteString(fmt.Sprintf("  async *%s(%s): AsyncGenerator<TypedStreamEvent<%s>> {\n",
		methodName, strings.Join(params, ", "), outputType))

	// Body.
	inputArg := "undefined"
	if op.Input != nil {
		inputArg = "input"
	}
	b.WriteString(fmt.Sprintf("    for await (const event of this.client.execute(\"%s\", %s, options)) {\n", op.Key, inputArg))
	b.WriteString(fmt.Sprintf("      yield event as TypedStreamEvent<%s>;\n", outputType))
	b.WriteString("    }\n")
	b.WriteString("  }\n")
}

func emitTSInterface(b *strings.Builder, td TypeDef) {
	if td.Description != "" {
		b.WriteString(tsDocComment(td.Description, ""))
	}
	b.WriteString(fmt.Sprintf("export interface %s {\n", td.Name))
	for _, f := range td.Fields {
		if f.Description != "" {
			b.WriteString(tsDocComment(f.Description, "  "))
		}
		opt := ""
		if !f.Required {
			opt = "?"
		}
		b.WriteString(fmt.Sprintf("  %s%s: %s;\n", f.JSONName, opt, tsTypeRef(f.Type)))
	}
	b.WriteString("}\n\n")
}

// tsTypeRef converts an IR TypeRef to a TypeScript type string.
func tsTypeRef(ref TypeRef) string {
	var base string
	switch ref.Kind {
	case KindPrimitive:
		if ref.Enum != nil {
			return tsEnumType(ref.Enum, ref.Nullable)
		}
		if ref.Const != nil {
			return tsConstType(ref.Const, ref.Nullable)
		}
		switch ref.Primitive {
		case "string":
			base = "string"
		case "number", "integer":
			base = "number"
		case "boolean":
			base = "boolean"
		default:
			base = "unknown"
		}
	case KindNamed:
		base = ref.Name
	case KindArray:
		if ref.Items != nil {
			itemType := tsTypeRef(*ref.Items)
			// Wrap the item type in parentheses whenever it renders as a
			// TypeScript union, otherwise `T[]` precedence binds the `[]`
			// to only the LAST variant of the union. This catches:
			//   - explicit unions (KindUnion)
			//   - nullable types (`T | null` from ref.Nullable)
			//   - enum primitives (`"a" | "b" | "c"` from KindPrimitive
			//     with Enum != nil)
			//   - const types with multiple values
			//
			// Detecting via string-search on " | " is the simplest correct
			// rule because it directly checks for the syntactic ambiguity.
			if strings.Contains(itemType, " | ") {
				base = fmt.Sprintf("(%s)[]", itemType)
			} else {
				base = fmt.Sprintf("%s[]", itemType)
			}
		} else {
			base = "unknown[]"
		}
	case KindMap:
		valType := "unknown"
		if ref.Values != nil {
			valType = tsTypeRef(*ref.Values)
		}
		base = fmt.Sprintf("Record<string, %s>", valType)
	case KindUnion:
		parts := make([]string, len(ref.Variants))
		for i, v := range ref.Variants {
			parts[i] = tsTypeRef(v)
		}
		base = strings.Join(parts, " | ")
	default:
		base = "unknown"
	}

	if ref.Nullable && ref.Kind != KindUnion {
		return base + " | null"
	}
	return base
}

func tsEnumType(values []any, nullable bool) string {
	parts := make([]string, len(values))
	for i, v := range values {
		switch val := v.(type) {
		case string:
			parts[i] = fmt.Sprintf("%q", val)
		case float64:
			if val == float64(int64(val)) {
				parts[i] = fmt.Sprintf("%d", int64(val))
			} else {
				parts[i] = fmt.Sprintf("%g", val)
			}
		default:
			parts[i] = fmt.Sprintf("%v", val)
		}
	}
	result := strings.Join(parts, " | ")
	if nullable {
		result += " | null"
	}
	return result
}

func tsConstType(val any, nullable bool) string {
	var s string
	switch v := val.(type) {
	case string:
		s = fmt.Sprintf("%q", v)
	case float64:
		if v == float64(int64(v)) {
			s = fmt.Sprintf("%d", int64(v))
		} else {
			s = fmt.Sprintf("%g", v)
		}
	case bool:
		s = fmt.Sprintf("%t", v)
	default:
		s = fmt.Sprintf("%v", v)
	}
	if nullable {
		return s + " | null"
	}
	return s
}

func tsDocComment(text, indent string) string {
	lines := strings.Split(text, "\n")
	if len(lines) == 1 {
		return fmt.Sprintf("%s/** %s */\n", indent, text)
	}
	var b strings.Builder
	b.WriteString(fmt.Sprintf("%s/**\n", indent))
	for _, line := range lines {
		b.WriteString(fmt.Sprintf("%s * %s\n", indent, line))
	}
	b.WriteString(fmt.Sprintf("%s */\n", indent))
	return b.String()
}

func tsEscapeSingleQuoteString(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "'", "\\'")
	return s
}
