package codegen

import (
	"fmt"
	"strings"
)

// EmitTypeScript generates a TypeScript signature file from a CodegenResult.
//
// The output is the per-operation input/output interfaces plus an
// OperationSignatures namespace: a const holding one branded
// OperationSignature<I, O> per operation, built with the SDK's
// `operationSignature` constructor. Callers invoke with the invoker method,
// supplying the runtime interface:
//
//	const call = invoker.invoke(obi, pkg.OperationSignatures.getMenu);
//	const out = await single(call.outputs);
//
// There are no per-operation methods, no bound invoker interface/factory, and
// no embedded contract: the interface is the runtime bundle, passed to invoke,
// never codegenned. Cardinality lives in the binding and the handle, never in
// the generated signature.
func EmitTypeScript(r *CodegenResult) string {
	var b strings.Builder

	b.WriteString("// Auto-generated by ob codegen — do not edit\n")
	b.WriteString(fmt.Sprintf("// Requires %s (the OperationSignature/invoke API).\n", TSSDKRange))
	b.WriteString("import { operationSignature } from \"@openbindings/sdk\";\n\n")

	// Types: per-operation I/O interfaces plus any named schemas they share. A
	// schema referenced by several operations is emitted once and reused, so
	// type identity is preserved across operations.
	if len(r.Types) > 0 {
		b.WriteString("// --- Types ---\n\n")
		for _, td := range r.Types {
			emitTSInterface(&b, td)
		}
	}

	// Operation signatures.
	b.WriteString("// --- Operation signatures ---\n\n")
	emitTSSignatures(&b, r)

	return b.String()
}

// emitTSSignatures writes the OperationSignatures const: one branded signature
// per operation, with each operation's description and deprecation on its
// property so they surface in editor hover.
func emitTSSignatures(b *strings.Builder, r *CodegenResult) {
	example := toCamelCase(r.Operations[0].Name)
	var doc strings.Builder
	doc.WriteString("OperationSignatures holds one typed signature per operation declared by")
	doc.WriteString("\nthe codegen-time OBI. Pass the runtime interface and a signature to")
	doc.WriteString("\n`invoker.invoke`; input flows through the handle's `write` and output")
	doc.WriteString("\nthrough `single` (the typed I/O is not a unary in/out shortcut):")
	doc.WriteString("\n")
	doc.WriteString(fmt.Sprintf("\n    const call = invoker.invoke(obi, OperationSignatures.%s);", example))
	doc.WriteString("\n    const out = await single(call.outputs);")
	b.WriteString(tsDocComment(doc.String(), ""))

	b.WriteString("export const OperationSignatures = {\n")
	for _, op := range r.Operations {
		emitTSSignatureField(b, op)
	}
	b.WriteString("} as const;\n")
}

func emitTSSignatureField(b *strings.Builder, op OperationSig) {
	fieldName := toCamelCase(op.Name)
	inputType, outputType := tsIOTypes(op)

	if op.Description != "" || op.Deprecated {
		b.WriteString("  /**\n")
		if op.Description != "" {
			b.WriteString(fmt.Sprintf("   * %s\n", op.Description))
		}
		if op.Deprecated {
			b.WriteString("   * @deprecated this operation is deprecated\n")
		}
		b.WriteString("   */\n")
	}
	b.WriteString(fmt.Sprintf("  %s: operationSignature<%s, %s>(%q),\n",
		fieldName, inputType, outputType, op.Key))
}

// tsIOTypes returns the I/O type parameters for an operation's signature. An
// operation with no declared input gets `never` (the binding closes the input
// side itself; the caller cannot write); an undeclared output is `unknown`.
func tsIOTypes(op OperationSig) (inputType, outputType string) {
	inputType = "never"
	if op.Input != nil {
		inputType = tsTypeRef(*op.Input)
	}
	outputType = "unknown"
	if op.Output != nil {
		outputType = tsTypeRef(*op.Output)
	}
	return inputType, outputType
}

func emitTSInterface(b *strings.Builder, td TypeDef) {
	if td.Description != "" {
		b.WriteString(tsDocComment(td.Description, ""))
	}
	b.WriteString(fmt.Sprintf("export interface %s {\n", td.Name))
	for _, f := range td.Fields {
		if f.Description != "" {
			b.WriteString(tsDocComment(f.Description, "  "))
		}
		opt := ""
		if !f.Required {
			opt = "?"
		}
		b.WriteString(fmt.Sprintf("  %s%s: %s;\n", f.JSONName, opt, tsTypeRef(f.Type)))
	}
	b.WriteString("}\n\n")
}

// tsTypeRef converts an IR TypeRef to a TypeScript type string.
func tsTypeRef(ref TypeRef) string {
	var base string
	switch ref.Kind {
	case KindPrimitive:
		if ref.Enum != nil {
			return tsEnumType(ref.Enum, ref.Nullable)
		}
		if ref.Const != nil {
			return tsConstType(ref.Const, ref.Nullable)
		}
		switch ref.Primitive {
		case "string":
			base = "string"
		case "number", "integer":
			base = "number"
		case "boolean":
			base = "boolean"
		default:
			base = "unknown"
		}
	case KindNamed:
		base = ref.Name
	case KindArray:
		if ref.Items != nil {
			itemType := tsTypeRef(*ref.Items)
			// Wrap the item type in parentheses whenever it renders as a
			// TypeScript union, otherwise `T[]` precedence binds the `[]`
			// to only the LAST variant of the union.
			if strings.Contains(itemType, " | ") {
				base = fmt.Sprintf("(%s)[]", itemType)
			} else {
				base = fmt.Sprintf("%s[]", itemType)
			}
		} else {
			base = "unknown[]"
		}
	case KindMap:
		valType := "unknown"
		if ref.Values != nil {
			valType = tsTypeRef(*ref.Values)
		}
		base = fmt.Sprintf("Record<string, %s>", valType)
	case KindUnion:
		parts := make([]string, len(ref.Variants))
		for i, v := range ref.Variants {
			parts[i] = tsTypeRef(v)
		}
		base = strings.Join(parts, " | ")
	default:
		base = "unknown"
	}

	if ref.Nullable && ref.Kind != KindUnion {
		return base + " | null"
	}
	return base
}

func tsEnumType(values []any, nullable bool) string {
	parts := make([]string, len(values))
	for i, v := range values {
		switch val := v.(type) {
		case string:
			parts[i] = fmt.Sprintf("%q", val)
		case float64:
			if val == float64(int64(val)) {
				parts[i] = fmt.Sprintf("%d", int64(val))
			} else {
				parts[i] = fmt.Sprintf("%g", val)
			}
		default:
			parts[i] = fmt.Sprintf("%v", val)
		}
	}
	result := strings.Join(parts, " | ")
	if nullable {
		result += " | null"
	}
	return result
}

func tsConstType(val any, nullable bool) string {
	var s string
	switch v := val.(type) {
	case string:
		s = fmt.Sprintf("%q", v)
	case float64:
		if v == float64(int64(v)) {
			s = fmt.Sprintf("%d", int64(v))
		} else {
			s = fmt.Sprintf("%g", v)
		}
	case bool:
		s = fmt.Sprintf("%t", v)
	default:
		s = fmt.Sprintf("%v", v)
	}
	if nullable {
		return s + " | null"
	}
	return s
}

func tsDocComment(text, indent string) string {
	lines := strings.Split(text, "\n")
	if len(lines) == 1 {
		return fmt.Sprintf("%s/** %s */\n", indent, text)
	}
	var b strings.Builder
	b.WriteString(fmt.Sprintf("%s/**\n", indent))
	for _, line := range lines {
		b.WriteString(fmt.Sprintf("%s * %s\n", indent, line))
	}
	b.WriteString(fmt.Sprintf("%s */\n", indent))
	return b.String()
}
