// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/blend/blend.proto

package blend

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoffeeShop_GetMenu_FullMethodName        = "/blend.CoffeeShop/GetMenu"
	CoffeeShop_PlaceOrder_FullMethodName     = "/blend.CoffeeShop/PlaceOrder"
	CoffeeShop_GetOrderStatus_FullMethodName = "/blend.CoffeeShop/GetOrderStatus"
	CoffeeShop_CancelOrder_FullMethodName    = "/blend.CoffeeShop/CancelOrder"
	CoffeeShop_OrderUpdates_FullMethodName   = "/blend.CoffeeShop/OrderUpdates"
)

// CoffeeShopClient is the client API for CoffeeShop service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CoffeeShop is the OpenBlendings service.
type CoffeeShopClient interface {
	// GetMenu returns the full menu with drinks, sizes, and prices.
	GetMenu(ctx context.Context, in *GetMenuRequest, opts ...grpc.CallOption) (*GetMenuResponse, error)
	// PlaceOrder places a new coffee order.
	PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error)
	// GetOrderStatus checks the current status of an order.
	GetOrderStatus(ctx context.Context, in *GetOrderStatusRequest, opts ...grpc.CallOption) (*GetOrderStatusResponse, error)
	// CancelOrder cancels a pending or preparing order.
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
	// OrderUpdates streams real-time order status changes.
	OrderUpdates(ctx context.Context, in *OrderUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OrderUpdate], error)
}

type coffeeShopClient struct {
	cc grpc.ClientConnInterface
}

func NewCoffeeShopClient(cc grpc.ClientConnInterface) CoffeeShopClient {
	return &coffeeShopClient{cc}
}

func (c *coffeeShopClient) GetMenu(ctx context.Context, in *GetMenuRequest, opts ...grpc.CallOption) (*GetMenuResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMenuResponse)
	err := c.cc.Invoke(ctx, CoffeeShop_GetMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coffeeShopClient) PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceOrderResponse)
	err := c.cc.Invoke(ctx, CoffeeShop_PlaceOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coffeeShopClient) GetOrderStatus(ctx context.Context, in *GetOrderStatusRequest, opts ...grpc.CallOption) (*GetOrderStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderStatusResponse)
	err := c.cc.Invoke(ctx, CoffeeShop_GetOrderStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coffeeShopClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelOrderResponse)
	err := c.cc.Invoke(ctx, CoffeeShop_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coffeeShopClient) OrderUpdates(ctx context.Context, in *OrderUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OrderUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoffeeShop_ServiceDesc.Streams[0], CoffeeShop_OrderUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OrderUpdatesRequest, OrderUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoffeeShop_OrderUpdatesClient = grpc.ServerStreamingClient[OrderUpdate]

// CoffeeShopServer is the server API for CoffeeShop service.
// All implementations must embed UnimplementedCoffeeShopServer
// for forward compatibility.
//
// CoffeeShop is the OpenBlendings service.
type CoffeeShopServer interface {
	// GetMenu returns the full menu with drinks, sizes, and prices.
	GetMenu(context.Context, *GetMenuRequest) (*GetMenuResponse, error)
	// PlaceOrder places a new coffee order.
	PlaceOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderResponse, error)
	// GetOrderStatus checks the current status of an order.
	GetOrderStatus(context.Context, *GetOrderStatusRequest) (*GetOrderStatusResponse, error)
	// CancelOrder cancels a pending or preparing order.
	CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error)
	// OrderUpdates streams real-time order status changes.
	OrderUpdates(*OrderUpdatesRequest, grpc.ServerStreamingServer[OrderUpdate]) error
	mustEmbedUnimplementedCoffeeShopServer()
}

// UnimplementedCoffeeShopServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoffeeShopServer struct{}

func (UnimplementedCoffeeShopServer) GetMenu(context.Context, *GetMenuRequest) (*GetMenuResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMenu not implemented")
}
func (UnimplementedCoffeeShopServer) PlaceOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaceOrder not implemented")
}
func (UnimplementedCoffeeShopServer) GetOrderStatus(context.Context, *GetOrderStatusRequest) (*GetOrderStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderStatus not implemented")
}
func (UnimplementedCoffeeShopServer) CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedCoffeeShopServer) OrderUpdates(*OrderUpdatesRequest, grpc.ServerStreamingServer[OrderUpdate]) error {
	return status.Error(codes.Unimplemented, "method OrderUpdates not implemented")
}
func (UnimplementedCoffeeShopServer) mustEmbedUnimplementedCoffeeShopServer() {}
func (UnimplementedCoffeeShopServer) testEmbeddedByValue()                    {}

// UnsafeCoffeeShopServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoffeeShopServer will
// result in compilation errors.
type UnsafeCoffeeShopServer interface {
	mustEmbedUnimplementedCoffeeShopServer()
}

func RegisterCoffeeShopServer(s grpc.ServiceRegistrar, srv CoffeeShopServer) {
	// If the following call panics, it indicates UnimplementedCoffeeShopServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoffeeShop_ServiceDesc, srv)
}

func _CoffeeShop_GetMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeShopServer).GetMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeShop_GetMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeShopServer).GetMenu(ctx, req.(*GetMenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoffeeShop_PlaceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeShopServer).PlaceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeShop_PlaceOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeShopServer).PlaceOrder(ctx, req.(*PlaceOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoffeeShop_GetOrderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeShopServer).GetOrderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeShop_GetOrderStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeShopServer).GetOrderStatus(ctx, req.(*GetOrderStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoffeeShop_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeShopServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeShop_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeShopServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoffeeShop_OrderUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OrderUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoffeeShopServer).OrderUpdates(m, &grpc.GenericServerStream[OrderUpdatesRequest, OrderUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoffeeShop_OrderUpdatesServer = grpc.ServerStreamingServer[OrderUpdate]

// CoffeeShop_ServiceDesc is the grpc.ServiceDesc for CoffeeShop service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoffeeShop_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blend.CoffeeShop",
	HandlerType: (*CoffeeShopServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMenu",
			Handler:    _CoffeeShop_GetMenu_Handler,
		},
		{
			MethodName: "PlaceOrder",
			Handler:    _CoffeeShop_PlaceOrder_Handler,
		},
		{
			MethodName: "GetOrderStatus",
			Handler:    _CoffeeShop_GetOrderStatus_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _CoffeeShop_CancelOrder_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OrderUpdates",
			Handler:       _CoffeeShop_OrderUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/blend/blend.proto",
}
