// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/blend/blend.proto

package blend

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuRequest) Reset() {
	*x = GetMenuRequest{}
	mi := &file_proto_blend_blend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuRequest) ProtoMessage() {}

func (x *GetMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blend_blend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuRequest.ProtoReflect.Descriptor instead.
func (*GetMenuRequest) Descriptor() ([]byte, []int) {
	return file_proto_blend_blend_proto_rawDescGZIP(), []int{0}
}

type GetMenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MenuItemMessage     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuResponse) Reset() {
	*x = GetMenuResponse{}
	mi := &file_proto_blend_blend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuResponse) ProtoMessage() {}

func (x *GetMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blend_blend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuResponse.ProtoReflect.Descriptor instead.
func (*GetMenuResponse) Descriptor() ([]byte, []int) {
	return file_proto_blend_blend_proto_rawDescGZIP(), []int{1}
}

func (x *GetMenuResponse) GetItems() []*MenuItemMessage {
	if x != nil {
		return x.Items
	}
	return nil
}

type MenuItemMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Sizes         []*SizePriceMessage    `protobuf:"bytes,4,rep,name=sizes,proto3" json:"sizes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItemMessage) Reset() {
	*x = MenuItemMessage{}
	mi := &file_proto_blend_blend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItemMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItemMessage) ProtoMessage() {}

func (x *MenuItemMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blend_blend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItemMessage.ProtoReflect.Descriptor instead.
func (*MenuItemMessage) Descriptor() ([]byte, []int) {
	return file_proto_blend_blend_proto_rawDescGZIP(), []int{2}
}

func (x *MenuItemMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuItemMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MenuItemMessage) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MenuItemMessage) GetSizes() []*SizePriceMessage {
	if x != nil {
		return x.Sizes
	}
	return nil
}

type SizePriceMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SizePriceMessage) Reset() {
	*x = SizePriceMessage{}
	mi := &file_proto_blend_blend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SizePriceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizePriceMessage) ProtoMessage() {}

func (x *SizePriceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blend_blend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizePriceMessage.ProtoReflect.Descriptor instead.
func (*SizePriceMessage) Descriptor() ([]byte, []int) {
	return file_proto_blend_blend_proto_rawDescGZIP(), []int{3}
}

func (x *SizePriceMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SizePriceMessage) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SizePriceMessage) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type PlaceOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drink         string                 `protobuf:"bytes,1,opt,name=drink,proto3" json:"drink,omitempty"`
	Size          string                 `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	Customer      string                 `protobuf:"bytes,3,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_proto_blend_blend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blend_blend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_blend_blend_proto_rawDescGZIP(), []int{4}
}

func (x *PlaceOrderRequest) GetDrink() string {
	if x != nil {
		return x.Drink
	}
	return ""
}

func (x *PlaceOrderRequest) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *PlaceOrderRequest) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

type PlaceOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Drink         string                 `protobuf:"bytes,3,opt,name=drink,proto3" json:"drink,omitempty"`
	Size          string                 `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	Customer      string                 `protobuf:"bytes,5,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderResponse) Reset() {
	*x = PlaceOrderResponse{}
	mi := &file_proto_blend_blend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResponse) ProtoMessage() {}

func (x *PlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blend_blend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_blend_blend_proto_rawDescGZIP(), []int{5}
}

func (x *PlaceOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PlaceOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PlaceOrderResponse) GetDrink() string {
	if x != nil {
		return x.Drink
	}
	return ""
}

func (x *PlaceOrderResponse) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *PlaceOrderResponse) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

type GetOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderStatusRequest) Reset() {
	*x = GetOrderStatusRequest{}
	mi := &file_proto_blend_blend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderStatusRequest) ProtoMessage() {}

func (x *GetOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blend_blend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*GetOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_blend_blend_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Drink         string                 `protobuf:"bytes,3,opt,name=drink,proto3" json:"drink,omitempty"`
	Size          string                 `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	Customer      string                 `protobuf:"bytes,5,opt,name=customer,proto3" json:"customer,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderStatusResponse) Reset() {
	*x = GetOrderStatusResponse{}
	mi := &file_proto_blend_blend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderStatusResponse) ProtoMessage() {}

func (x *GetOrderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blend_blend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderStatusResponse.ProtoReflect.Descriptor instead.
func (*GetOrderStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_blend_blend_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrderStatusResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOrderStatusResponse) GetDrink() string {
	if x != nil {
		return x.Drink
	}
	return ""
}

func (x *GetOrderStatusResponse) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *GetOrderStatusResponse) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

func (x *GetOrderStatusResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetOrderStatusResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_proto_blend_blend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blend_blend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_blend_blend_proto_rawDescGZIP(), []int{8}
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_proto_blend_blend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blend_blend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_blend_blend_proto_rawDescGZIP(), []int{9}
}

func (x *CancelOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type OrderUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderUpdatesRequest) Reset() {
	*x = OrderUpdatesRequest{}
	mi := &file_proto_blend_blend_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdatesRequest) ProtoMessage() {}

func (x *OrderUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blend_blend_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdatesRequest.ProtoReflect.Descriptor instead.
func (*OrderUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_blend_blend_proto_rawDescGZIP(), []int{10}
}

type OrderUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Drink         string                 `protobuf:"bytes,3,opt,name=drink,proto3" json:"drink,omitempty"`
	Customer      string                 `protobuf:"bytes,4,opt,name=customer,proto3" json:"customer,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderUpdate) Reset() {
	*x = OrderUpdate{}
	mi := &file_proto_blend_blend_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdate) ProtoMessage() {}

func (x *OrderUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blend_blend_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdate.ProtoReflect.Descriptor instead.
func (*OrderUpdate) Descriptor() ([]byte, []int) {
	return file_proto_blend_blend_proto_rawDescGZIP(), []int{11}
}

func (x *OrderUpdate) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderUpdate) GetDrink() string {
	if x != nil {
		return x.Drink
	}
	return ""
}

func (x *OrderUpdate) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

func (x *OrderUpdate) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_proto_blend_blend_proto protoreflect.FileDescriptor

const file_proto_blend_blend_proto_rawDesc = "" +
	"\n" +
	"\x17proto/blend/blend.proto\x12\x05blend\"\x10\n" +
	"\x0eGetMenuRequest\"?\n" +
	"\x0fGetMenuResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.blend.MenuItemMessageR\x05items\"\x92\x01\n" +
	"\x0fMenuItemMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12-\n" +
	"\x05sizes\x18\x04 \x03(\v2\x17.blend.SizePriceMessageR\x05sizes\"N\n" +
	"\x10SizePriceMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"Y\n" +
	"\x11PlaceOrderRequest\x12\x14\n" +
	"\x05drink\x18\x01 \x01(\tR\x05drink\x12\x12\n" +
	"\x04size\x18\x02 \x01(\tR\x04size\x12\x1a\n" +
	"\bcustomer\x18\x03 \x01(\tR\bcustomer\"\x8d\x01\n" +
	"\x12PlaceOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05drink\x18\x03 \x01(\tR\x05drink\x12\x12\n" +
	"\x04size\x18\x04 \x01(\tR\x04size\x12\x1a\n" +
	"\bcustomer\x18\x05 \x01(\tR\bcustomer\"2\n" +
	"\x15GetOrderStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\xcf\x01\n" +
	"\x16GetOrderStatusResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05drink\x18\x03 \x01(\tR\x05drink\x12\x12\n" +
	"\x04size\x18\x04 \x01(\tR\x04size\x12\x1a\n" +
	"\bcustomer\x18\x05 \x01(\tR\bcustomer\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"/\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"H\n" +
	"\x13CancelOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x15\n" +
	"\x13OrderUpdatesRequest\"\x90\x01\n" +
	"\vOrderUpdate\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05drink\x18\x03 \x01(\tR\x05drink\x12\x1a\n" +
	"\bcustomer\x18\x04 \x01(\tR\bcustomer\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp2\xe0\x02\n" +
	"\n" +
	"CoffeeShop\x128\n" +
	"\aGetMenu\x12\x15.blend.GetMenuRequest\x1a\x16.blend.GetMenuResponse\x12A\n" +
	"\n" +
	"PlaceOrder\x12\x18.blend.PlaceOrderRequest\x1a\x19.blend.PlaceOrderResponse\x12M\n" +
	"\x0eGetOrderStatus\x12\x1c.blend.GetOrderStatusRequest\x1a\x1d.blend.GetOrderStatusResponse\x12D\n" +
	"\vCancelOrder\x12\x19.blend.CancelOrderRequest\x1a\x1a.blend.CancelOrderResponse\x12@\n" +
	"\fOrderUpdates\x12\x1a.blend.OrderUpdatesRequest\x1a\x12.blend.OrderUpdate0\x01B*Z(github.com/openbindings/demo/proto/blendb\x06proto3"

var (
	file_proto_blend_blend_proto_rawDescOnce sync.Once
	file_proto_blend_blend_proto_rawDescData []byte
)

func file_proto_blend_blend_proto_rawDescGZIP() []byte {
	file_proto_blend_blend_proto_rawDescOnce.Do(func() {
		file_proto_blend_blend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_blend_blend_proto_rawDesc), len(file_proto_blend_blend_proto_rawDesc)))
	})
	return file_proto_blend_blend_proto_rawDescData
}

var file_proto_blend_blend_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_blend_blend_proto_goTypes = []any{
	(*GetMenuRequest)(nil),         // 0: blend.GetMenuRequest
	(*GetMenuResponse)(nil),        // 1: blend.GetMenuResponse
	(*MenuItemMessage)(nil),        // 2: blend.MenuItemMessage
	(*SizePriceMessage)(nil),       // 3: blend.SizePriceMessage
	(*PlaceOrderRequest)(nil),      // 4: blend.PlaceOrderRequest
	(*PlaceOrderResponse)(nil),     // 5: blend.PlaceOrderResponse
	(*GetOrderStatusRequest)(nil),  // 6: blend.GetOrderStatusRequest
	(*GetOrderStatusResponse)(nil), // 7: blend.GetOrderStatusResponse
	(*CancelOrderRequest)(nil),     // 8: blend.CancelOrderRequest
	(*CancelOrderResponse)(nil),    // 9: blend.CancelOrderResponse
	(*OrderUpdatesRequest)(nil),    // 10: blend.OrderUpdatesRequest
	(*OrderUpdate)(nil),            // 11: blend.OrderUpdate
}
var file_proto_blend_blend_proto_depIdxs = []int32{
	2,  // 0: blend.GetMenuResponse.items:type_name -> blend.MenuItemMessage
	3,  // 1: blend.MenuItemMessage.sizes:type_name -> blend.SizePriceMessage
	0,  // 2: blend.CoffeeShop.GetMenu:input_type -> blend.GetMenuRequest
	4,  // 3: blend.CoffeeShop.PlaceOrder:input_type -> blend.PlaceOrderRequest
	6,  // 4: blend.CoffeeShop.GetOrderStatus:input_type -> blend.GetOrderStatusRequest
	8,  // 5: blend.CoffeeShop.CancelOrder:input_type -> blend.CancelOrderRequest
	10, // 6: blend.CoffeeShop.OrderUpdates:input_type -> blend.OrderUpdatesRequest
	1,  // 7: blend.CoffeeShop.GetMenu:output_type -> blend.GetMenuResponse
	5,  // 8: blend.CoffeeShop.PlaceOrder:output_type -> blend.PlaceOrderResponse
	7,  // 9: blend.CoffeeShop.GetOrderStatus:output_type -> blend.GetOrderStatusResponse
	9,  // 10: blend.CoffeeShop.CancelOrder:output_type -> blend.CancelOrderResponse
	11, // 11: blend.CoffeeShop.OrderUpdates:output_type -> blend.OrderUpdate
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_blend_blend_proto_init() }
func file_proto_blend_blend_proto_init() {
	if File_proto_blend_blend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_blend_blend_proto_rawDesc), len(file_proto_blend_blend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_blend_blend_proto_goTypes,
		DependencyIndexes: file_proto_blend_blend_proto_depIdxs,
		MessageInfos:      file_proto_blend_blend_proto_msgTypes,
	}.Build()
	File_proto_blend_blend_proto = out.File
	file_proto_blend_blend_proto_goTypes = nil
	file_proto_blend_blend_proto_depIdxs = nil
}
