// One dispatch identity per domain command; no implementation is attached yet.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum CommandId {
    Init,
    Show,
    Set,
    Validate,
    Diff,
    Compat,
    Fmt,
    Patch,
    Merge,
    OperationAdd,
    OperationSet,
    OperationRename,
    OperationRemove,
    OperationList,
    OperationShow,
    OperationExampleAdd,
    OperationExampleSet,
    OperationExampleRename,
    OperationExampleRemove,
    OperationExampleList,
    OperationExampleShow,
    SourceAdd,
    SourceSet,
    SourceRename,
    SourceRemove,
    SourceList,
    SourceShow,
    SourceImport,
    SourceInspect,
    SourcePull,
    BindingAdd,
    BindingSet,
    BindingRename,
    BindingRemove,
    BindingList,
    BindingShow,
    DependencyAdd,
    DependencySet,
    DependencyRename,
    DependencyRemove,
    DependencyList,
    DependencyShow,
    SchemaAdd,
    SchemaSet,
    SchemaRename,
    SchemaRemove,
    SchemaList,
    SchemaShow,
    SchemaBundle,
    Synthesize,
    Status,
    Fetch,
    Invoke,
    ContextSet,
    ContextList,
    ContextShow,
    ContextRemove,
    Codegen,
    Start,
    Mcp,
    CaInstall,
    CaRemove,
    CaShow,
    KindList,
    KindCheck,
    DelegateRoles,
    DelegateAdd,
    DelegateSet,
    DelegateRemove,
    DelegateList,
    DelegateShow,
    DelegateResolve,
    Describe,
}
impl CommandId {
    pub(crate) fn from_path(path: &str) -> Option<Self> {
        match path {
            "ob init" => Some(Self::Init),
            "ob show" => Some(Self::Show),
            "ob set" => Some(Self::Set),
            "ob validate" => Some(Self::Validate),
            "ob diff" => Some(Self::Diff),
            "ob compat" => Some(Self::Compat),
            "ob fmt" => Some(Self::Fmt),
            "ob patch" => Some(Self::Patch),
            "ob merge" => Some(Self::Merge),
            "ob operation add" => Some(Self::OperationAdd),
            "ob operation set" => Some(Self::OperationSet),
            "ob operation rename" => Some(Self::OperationRename),
            "ob operation remove" => Some(Self::OperationRemove),
            "ob operation list" => Some(Self::OperationList),
            "ob operation show" => Some(Self::OperationShow),
            "ob operation example add" => Some(Self::OperationExampleAdd),
            "ob operation example set" => Some(Self::OperationExampleSet),
            "ob operation example rename" => Some(Self::OperationExampleRename),
            "ob operation example remove" => Some(Self::OperationExampleRemove),
            "ob operation example list" => Some(Self::OperationExampleList),
            "ob operation example show" => Some(Self::OperationExampleShow),
            "ob source add" => Some(Self::SourceAdd),
            "ob source set" => Some(Self::SourceSet),
            "ob source rename" => Some(Self::SourceRename),
            "ob source remove" => Some(Self::SourceRemove),
            "ob source list" => Some(Self::SourceList),
            "ob source show" => Some(Self::SourceShow),
            "ob source import" => Some(Self::SourceImport),
            "ob source inspect" => Some(Self::SourceInspect),
            "ob source pull" => Some(Self::SourcePull),
            "ob binding add" => Some(Self::BindingAdd),
            "ob binding set" => Some(Self::BindingSet),
            "ob binding rename" => Some(Self::BindingRename),
            "ob binding remove" => Some(Self::BindingRemove),
            "ob binding list" => Some(Self::BindingList),
            "ob binding show" => Some(Self::BindingShow),
            "ob dependency add" => Some(Self::DependencyAdd),
            "ob dependency set" => Some(Self::DependencySet),
            "ob dependency rename" => Some(Self::DependencyRename),
            "ob dependency remove" => Some(Self::DependencyRemove),
            "ob dependency list" => Some(Self::DependencyList),
            "ob dependency show" => Some(Self::DependencyShow),
            "ob schema add" => Some(Self::SchemaAdd),
            "ob schema set" => Some(Self::SchemaSet),
            "ob schema rename" => Some(Self::SchemaRename),
            "ob schema remove" => Some(Self::SchemaRemove),
            "ob schema list" => Some(Self::SchemaList),
            "ob schema show" => Some(Self::SchemaShow),
            "ob schema bundle" => Some(Self::SchemaBundle),
            "ob synthesize" => Some(Self::Synthesize),
            "ob status" => Some(Self::Status),
            "ob fetch" => Some(Self::Fetch),
            "ob invoke" => Some(Self::Invoke),
            "ob context set" => Some(Self::ContextSet),
            "ob context list" => Some(Self::ContextList),
            "ob context show" => Some(Self::ContextShow),
            "ob context remove" => Some(Self::ContextRemove),
            "ob codegen" => Some(Self::Codegen),
            "ob start" => Some(Self::Start),
            "ob mcp" => Some(Self::Mcp),
            "ob ca install" => Some(Self::CaInstall),
            "ob ca remove" => Some(Self::CaRemove),
            "ob ca show" => Some(Self::CaShow),
            "ob kind list" => Some(Self::KindList),
            "ob kind check" => Some(Self::KindCheck),
            "ob delegate roles" => Some(Self::DelegateRoles),
            "ob delegate add" => Some(Self::DelegateAdd),
            "ob delegate set" => Some(Self::DelegateSet),
            "ob delegate remove" => Some(Self::DelegateRemove),
            "ob delegate list" => Some(Self::DelegateList),
            "ob delegate show" => Some(Self::DelegateShow),
            "ob delegate resolve" => Some(Self::DelegateResolve),
            "ob describe" => Some(Self::Describe),
            _ => None,
        }
    }
}
